import type { Metadata } from "next";
import "./globals.css";
import {Montserrat} from "next/font/google";
import classNames from "classnames";
import QueryProvider from "@/providers/QueryProvider";

const montserrat = Montserrat({
    subsets: ['latin'],
    display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(montserrat.className, 'antialiased')}
      >
          <QueryProvider>
            <main className="container mx-auto px-4">
                {children}
            </main>
          </QueryProvider>
      </body>
    </html>
  );
}
